package com.revealprecision.revealstreams.persistence.repository;

import com.cosium.spring.data.jpa.entity.graph.repository.EntityGraphJpaRepository;
import com.revealprecision.revealstreams.persistence.domain.HdssCompounds;
import com.revealprecision.revealstreams.persistence.projection.GdrsCountsProjection;
import com.revealprecision.revealstreams.persistence.projection.HdssEventDataProjection;
import com.revealprecision.revealstreams.persistence.projection.IndividualTaskBusinessStateByLocationProjection;
import com.revealprecision.revealstreams.persistence.projection.IndividualsByLocationProjection;
import com.revealprecision.revealstreams.persistence.projection.IndividualsPerCompoundByLocationProjection;
import java.util.List;
import java.util.UUID;
import org.springframework.data.jpa.repository.Query;

public interface HdssCompoundsRepository extends EntityGraphJpaRepository<HdssCompounds, UUID> {

  @Query(value = "SELECT cast(lp.identifier as varchar) as locationIdentifier, lp.name as locationName,count(*) as individualCount\n"
      + "from hdss.hdss_compounds hc\n"
      + "left join (SELECT lr.location_identifier as child_location, arr.ancestor\n"
      + "        from location_relationship lr,\n"
      + "             unnest(lr.ancestry) with ordinality arr(ancestor, pos)\n"
      + "        ) as lr on lr.child_location = hc.structure_id\n"
      + "left join location lp on lr.ancestor = lp.identifier\n"
      + "left join geographic_level gl on gl.identifier = lp.geographic_level_identifier\n"
      + "where lp.identifier = :locationIdentifier\n"
      + "group by lp.identifier,lp.name;",nativeQuery = true)
  IndividualsByLocationProjection getNumberOfIndividualsByLocation(UUID locationIdentifier);


  @Query(value = "SELECT  hc.compound_id as compound ,count(*) as individualCount\n"
      + "from hdss.hdss_compounds hc\n"
      + "         left join (SELECT lr.location_identifier as child_location, arr.ancestor\n"
      + "                    from location_relationship lr,\n"
      + "                         unnest(lr.ancestry) with ordinality arr(ancestor, pos)\n"
      + ") as lr on lr.child_location = hc.structure_id\n"
      + "         left join location lp on lr.ancestor = lp.identifier\n"
      + "         left join geographic_level gl on gl.identifier = lp.geographic_level_identifier\n"
      + "where lp.identifier = :locationIdentifier \n"
      + "group by hc.compound_id",nativeQuery = true)

  List<IndividualsPerCompoundByLocationProjection> getNumberOfIndividualsPerCompoundByLocation(UUID locationIdentifier);

  @Query(value = "SELECT c.parentName,\n"
      + "       cast(c.childIdentifier as varchar)  as locationIdentifier,\n"
      + "       c.childName ,\n"
      + "       count(*) as individualCount\n"
      + "From (\n"
      + "         SELECT DISTINCT l.name as parentName,\n"
      + "                         cl.identifier as childIdentifier,\n"
      + "                         cl.name as childName ,\n"
      + "                         hc.individual_id\n"
      + "         from location l\n"
      + "                  left join location_relationship lr on lr.parent_identifier = l.identifier\n"
      + "                  left join (\n"
      + "             SELECT lr.location_identifier, parent.parent_id\n"
      + "             from location_relationship lr,\n"
      + "                  unnest(lr.ancestry) with ordinality parent(parent_id, pos)\n"
      + "         ) p on p.parent_id = lr.location_identifier\n"
      + "                  left join location cl on cl.identifier = lr.location_identifier\n"
      + "\n"
      + "                  left join hdss.hdss_compounds hc on hc.structure_id = p.location_identifier\n"
      + "         WHERE l.identifier = :locationIdentifier\n"
      + "\n"
      + "     ) c\n"
      + "group by c.parentName,c.childIdentifier,c.childName",nativeQuery = true)

  List<IndividualsPerCompoundByLocationProjection>  getListOfNumberOfIndividualsByLocation(UUID locationIdentifier);


  @Query(value = "SELECT a.title as title, t.business_status as businessStatus, count(*) as businessStatusCount\n"
      + "from task t\n"
      + "    left join action a on a.identifier = t.action_identifier\n"
      + "         inner join person p on p.identifier = t.base_entity_identifier\n"
      + "         inner join person_location pl on pl.person_identifier = p.identifier\n"
      + "    inner join (SELECT lr.location_identifier as child_location, arr.ancestor\n"
      + "               from location_relationship lr,\n"
      + "                    unnest(lr.ancestry) with ordinality arr(ancestor, pos)\n"
      + "                ) as lr on lr.child_location = pl.location_identifier\n"
      + "    left join location lp on lr.ancestor = lp.identifier\n"
      + "    left join geographic_level gl on gl.identifier = lp.geographic_level_identifier\n"
      + "where\n"
      + "      t.plan_identifier = :planIdentifier\n"
      + "  and lp.identifier = :locationIdentifier\n"
      + "group by a.title, t.business_status", nativeQuery = true)
  List<IndividualTaskBusinessStateByLocationProjection> getTaskBusinessStateCountsByLocation(UUID planIdentifier,UUID locationIdentifier);


  @Query(value = "SELECT count(*)\n"
      + "From (\n"
      + "         SELECT DISTINCT \n"
      + "            e.observations -> 'rdt' ->> 0        as rdt,\n"
      + "            e.observations -> 'individual' ->> 0 AS individual,\n"
      + "            hc.*,\n"
      + "            l.name\n"
      + "         FROM event_tracker e\n"
      + "                  left join hdss.hdss_compounds hc\n"
      + "                            on hc.individual_id = e.observations -> 'individual' ->> 0\n"
      + "                  left join (\n"
      + "             SELECT lr.location_identifier, parent.parent_id\n"
      + "             from location_relationship lr,\n"
      + "                  unnest(lr.ancestry) with ordinality parent(parent_id, pos)\n"
      + "         ) p on p.location_identifier = hc.structure_id\n"
      + "                  left join location l on l.identifier = parent_id\n"
      + "         WHERE e.observations -> 'individual' -> 0 IS NOT NULL\n"
      + "           and e.observations -> 'rdt' -> 0 is not null\n"
      + "           and l.identifier = :locationIdentifier \n"
      + "     ) c",nativeQuery = true)
  int getNumberOfTestedIndividualsByLocation(UUID locationIdentifier);

  @Query(value = "SELECT cast(c.locationIdentifier as varchar) as locationIdentifier,c.compound_id as compound,\n"
      + "       sum(c.pas_tested)   as passiveTested,\n"
      + "       sum(c.rcd_tested) as rcdTested,\n"
      + "       sum(c.pas_positive) as passivePositive,\n"
      + "       sum(c.rcd_positive) as rcdPositive,\n"
      + "       sum(c.pas_tested + c.rcd_tested) as totalTested,\n"
      + "       sum(c.rcd_positive + c.pas_positive) as totalCases\n"
      + " From ( "
      + "         SELECT DISTINCT CASE\n"
      + "                             WHEN e.observations -> 'rdt' ->> 0 = 'Positive' AND e.event_type = 'passive_case_detection' THEN 1\n"
      + "                             ELSE 0 END                                                      as pas_positive,\n"
      + "                         CASE\n"
      + "                             WHEN e.observations -> 'rdt' ->> 0 = 'Positive' AND e.event_type = 'rcd' THEN 1\n"
      + "                             ELSE 0 END                                                      as rcd_positive,\n"
      + "                         CASE\n"
      + "                             WHEN e.observations -> 'rdt' ->> 0 = 'Positive' AND e.event_type = 'passive_case_detection'\n"
      + "                                 OR e.observations -> 'rdt' ->> 0 = 'Negative' AND e.event_type = 'passive_case_detection' THEN 1\n"
      + "                             ELSE 0 END                                                      as pas_tested,\n"
      + "                         CASE\n"
      + "                             WHEN e.observations -> 'rdt' ->> 0 = 'Positive' AND e.event_type = 'rcd'\n"
      + "                                 OR e.observations -> 'rdt' ->> 0 = 'Negative' AND e.event_type = 'rcd' THEN 1\n"
      + "                             ELSE 0 END                                                      as rcd_tested,\n"
      + "                         hc.compound_id,\n"
      + "                          hc.structure_id as locationIdentifier,\n"
      + "                         hc.individual_id\n"
      + "         FROM event_tracker e\n"
      + "                  left join hdss.hdss_compounds hc\n"
      + "                            on hc.individual_id = e.observations -> 'individual' ->> 0\n"
      + "                  left join (\n"
      + "             SELECT lr.location_identifier, parent.parent_id\n"
      + "             from location_relationship lr,\n"
      + "                  unnest(lr.ancestry) with ordinality parent(parent_id, pos)\n"
      + "         ) p on p.location_identifier = hc.structure_id\n"
      + "                  left join location l on l.identifier = parent_id\n"
      + "         WHERE\n"
      + "               l.identifier = :locationIdentifier \n"
      + "           and e.plan_identifier = :planIdentifier\n"
      + "     ) c\n"
      + "group by c.compound_id,cast(c.locationIdentifier as varchar) ;",nativeQuery = true)
  List<HdssEventDataProjection> getEventDataForLocationAndPlan(UUID locationIdentifier, UUID planIdentifier);

  @Query(value = "SELECT c.parentName,\n"
      + "       cast(c.childIdentifier as varchar) as locationIdentifier,\n"
      + "       c.childName as childName,\n"
      + "       sum(c.pas_tested)                    as passiveTested,\n"
      + "       sum(c.rcd_tested)                    as rcdTested,\n"
      + "       sum(c.pas_positive)                  as passivePositive,\n"
      + "       sum(c.rcd_positive)                  as rcdPositive,\n"
      + "       sum(c.pas_tested + c.rcd_tested)     as totalTested,\n"
      + "       sum(c.rcd_positive + c.pas_positive) as totalCases\n"
      + "From (\n"
      + "         SELECT DISTINCT l.name as parentName,\n"
      + "                         cl.identifier as childIdentifier,\n"
      + "                         cl.name as childName,\n"
      + "                         hc.individual_id,\n"
      + "                         CASE\n"
      + "                             WHEN e.observations -> 'rdt' ->> 0 = 'Positive' AND\n"
      + "                                  e.event_type = 'passive_case_detection' THEN 1\n"
      + "                             ELSE 0 END as pas_positive,\n"
      + "                         CASE\n"
      + "                             WHEN e.observations -> 'rdt' ->> 0 = 'Positive' AND\n"
      + "                                  e.event_type = 'rcd' THEN 1\n"
      + "                             ELSE 0 END as rcd_positive,\n"
      + "                         CASE\n"
      + "                             WHEN e.observations -> 'rdt' ->> 0 = 'Positive' AND\n"
      + "                                  e.event_type = 'passive_case_detection'\n"
      + "                                 OR e.observations -> 'rdt' ->> 0 = 'Negative' AND\n"
      + "                                    e.event_type = 'passive_case_detection' THEN 1\n"
      + "                             ELSE 0 END as pas_tested,\n"
      + "                         CASE\n"
      + "                             WHEN e.observations -> 'rdt' ->> 0 = 'Positive' AND\n"
      + "                                  e.event_type = 'rcd'\n"
      + "                                 OR e.observations -> 'rdt' ->> 0 = 'Negative' AND\n"
      + "                                    e.event_type = 'rcd' THEN 1\n"
      + "                             ELSE 0 END as rcd_tested\n"
      + "         from location l\n"
      + "                  left join location_relationship lr on lr.parent_identifier = l.identifier\n"
      + "                  left join (\n"
      + "             SELECT lr.location_identifier, parent.parent_id\n"
      + "             from location_relationship lr,\n"
      + "                  unnest(lr.ancestry) with ordinality parent(parent_id, pos)\n"
      + "         ) p on p.parent_id = lr.location_identifier\n"
      + "                  left join location cl on cl.identifier = lr.location_identifier\n"
      + "                  left join hdss.hdss_compounds hc on hc.structure_id = p.location_identifier\n"
      + "                  left join event_tracker e\n"
      + "                             on hc.individual_id = e.observations -> 'individual' ->> 0\n"
      + "         WHERE l.identifier = :locationIdentifier\n"
      + "           and (e.plan_identifier = :planIdentifier  OR e.identifier IS NULL)\n"
      + "\n"
      + "     ) c\n"
      + "group by c.parentName,c.childIdentifier,c.childName",nativeQuery = true)
  List<HdssEventDataProjection> getEventDataForLocationAndPlanBelowHighest(UUID locationIdentifier, UUID planIdentifier);


  @Query(value = "SELECT p.rdt,\n"
      + "       CAST(p.parIdentifier as VARCHAR) as parIdentifier,\n"
      + "       p.parName,\n"
      + "       p.parGeo,\n"
      + "       count(*) as count\n"
      + "FROM (\n"
      + "         SELECT g.type,\n"
      + "                g.barcode,\n"
      + "                l.location_property ->> 'geographicLevel'  as locGeo,\n"
      + "                g.rdt,\n"
      + "                pl.identifier as parIdentifier,\n"
      + "                pl.name                                    as parName,\n"
      + "                pl.location_property ->> 'geographicLevel' as parGeo\n"
      + "         from (SELECT DISTINCT 'rcd'                                                   as type,\n"
      + "                               e.additional_information -> 'details' ->> 'location_id' as locationIdentifier,\n"
      + "                               arr.val ->> 'rcd_barcode'                               as barcode,\n"
      + "                               arr.val ->> 'rdt'                                       as rdt,\n"
      + "                               arr.val ->> 'individual'                                as individual\n"
      + "               From event e,\n"
      + "                    LATERAL extract_obs_fields_dynamic(\n"
      + "                            e.additional_information,\n"
      + "                            CAST(ARRAY ['rdt','rcd_barcode','individual'] as text[])) with ordinality arr(val, pos)\n"
      + "\n"
      + "               where e.event_type = 'rcd'\n"
      + "                 and arr.val ->> 'rdt' IS NOT NULL and e.plan_identifier = :planIdentifier\n"
      + "              ) as g\n"
      + "                  left join location l\n"
      + "                            on cast(l.identifier as varchar) = g.locationIdentifier\n"
      + "                  left join (\n"
      + "             SELECT arr.parent, lr.location_identifier\n"
      + "             from location_relationship lr,\n"
      + "                  LATERAL unnest(array_append(lr.ancestry, lr.location_identifier))\n"
      + "                      WITH ORDINALITY arr(parent, position)) lr\n"
      + "                            on cast(lr.location_identifier as varchar) =\n"
      + "                               g.locationIdentifier\n"
      + "                  left join location pl on pl.identifier = lr.parent\n"
      + "     ) as p\n"
      + "left join location_relationship pplr on p.parIdentifier = pplr.location_identifier\n"
      + "left join location pl on pl.identifier = pplr.parent_identifier\n"
      + "WHERE pl.location_property ->> 'geographicLevel'= :geographicLevel and p.parIdentifier IS NOT NULL\n"
      + "group by p.rdt,\n"
      + "         p.parIdentifier,p.parName, p.parGeo", nativeQuery = true)
  List<GdrsCountsProjection> getRCDCounts(String geographicLevel,UUID planIdentifier);

  @Query(value = "SELECT p.rdt,\n"
      + "       CAST(p.parIdentifier as VARCHAR) as parIdentifier,\n"
      + "       p.parName,\n"
      + "       p.parGeo,\n"
      + "       count(*) as count\n"
      + "FROM (\n"
      + "         SELECT g.type,\n"
      + "                g.barcode,\n"
      + "                l.location_property ->> 'geographicLevel'  as locGeo,\n"
      + "                g.rdt,\n"
      + "                pl.identifier as parIdentifier,\n"
      + "                pl.name                                    as parName,\n"
      + "                pl.location_property ->> 'geographicLevel' as parGeo\n"
      + "         from (SELECT DISTINCT 'rcd'                                                   as type,\n"
      + "                               e.additional_information -> 'details' ->> 'location_id' as locationIdentifier,\n"
      + "                               arr.val ->> 'rcd_barcode'                               as barcode,\n"
      + "                               arr.val ->> 'rdt'                                       as rdt,\n"
      + "                               arr.val ->> 'individual'                                as individual\n"
      + "               From event e,\n"
      + "                    LATERAL extract_obs_fields_dynamic(\n"
      + "                            e.additional_information,\n"
      + "                            CAST(ARRAY ['rdt','rcd_barcode','individual'] as text[])) with ordinality arr(val, pos)\n"
      + "\n"
      + "               where e.event_type = 'rcd'\n"
      + "                 and arr.val ->> 'rdt' IS NOT NULL and e.plan_identifier = :planIdentifier\n"
      + "              ) as g\n"
      + "                  left join location l\n"
      + "                            on cast(l.identifier as varchar) = g.locationIdentifier\n"
      + "                  left join (\n"
      + "             SELECT arr.parent, lr.location_identifier\n"
      + "             from location_relationship lr,\n"
      + "                  LATERAL unnest(array_append(lr.ancestry, lr.location_identifier))\n"
      + "                      WITH ORDINALITY arr(parent, position)) lr\n"
      + "                            on cast(lr.location_identifier as varchar) =\n"
      + "                               g.locationIdentifier\n"
      + "                  left join location pl on pl.identifier = lr.parent\n"
      + "     ) as p\n"
      + "left join location_relationship pplr on p.parIdentifier = pplr.location_identifier\n"
      + "left join location pl on pl.identifier = pplr.parent_identifier\n"
      + "WHERE pl.location_property ->> 'geographicLevel' is null and p.parIdentifier IS NOT NULL\n"
      + "group by p.rdt,\n"
      + "         p.parIdentifier,p.parName, p.parGeo", nativeQuery = true)
  List<GdrsCountsProjection> getHighestLevelRCDCounts(UUID planIdentifier);


  @Query(value = "SELECT p.rdt,\n"
      + "       CAST(p.parIdentifier as VARCHAR) as parIdentifier,\n"
      + "       p.parName,\n"
      + "       p.parGeo\n"
      + "        ,count(*)\n"
      + "FROM (\n"
      + "         SELECT g.type,\n"
      + "                g.barcode,\n"
      + "                l.location_property ->> 'geographicLevel'  as locGeo,\n"
      + "                g.rdt,\n"
      + "                pl.identifier as parIdentifier,\n"
      + "                pl.name                                    as parName,\n"
      + "                pl.location_property ->> 'geographicLevel' as parGeo\n"
      + "         FROM (\n"
      + "                  SELECT DISTINCT 'passive'                                     as type,\n"
      + "                                  CASE\n"
      + "                                      WHEN t.locIdentifier IS NULL\n"
      + "                                          THEN CAST(t.eventLocationIdentifier as varchar)\n"
      + "                                      ELSE CAST(t.locIdentifier as varchar) END as locationIdentifier,\n"
      + "                                  t.barcode,\n"
      + "                                  t.rdt,\n"
      + "                                  t.individual\n"
      + "\n"
      + "                  FROM (\n"
      + "                           SELECT l.identifier              as locIdentifier,\n"
      + "                                  arr.val ->> 'rcd_barcode' as barcode,\n"
      + "                                  arr.val ->> 'rdt'         as rdt,\n"
      + "                                  arr.val ->> 'individual'  as individual,\n"
      + "                                  e.location_identifier     as eventLocationIdentifier\n"
      + "                           from event e,\n"
      + "                                LATERAL extract_obs_fields_dynamic(\n"
      + "                                        e.additional_information,\n"
      + "                                        CAST(ARRAY ['rdt','cluster','rcd_barcode','individual'] as text[])) with ordinality arr(val, pos)\n"
      + "                                    left join location l on l.name = arr.val ->> 'cluster'\n"
      + "                           WHERE e.event_type = 'passive_case_detection'\n"
      + "                             and arr.val ->> 'rdt' is not null and e.plan_identifier = :planIdentifier\n"
      + "                       ) as t) as g\n"
      + "                  left join location l\n"
      + "                            on cast(l.identifier as varchar) = g.locationIdentifier\n"
      + "                  left join (\n"
      + "             SELECT arr.parent, lr.location_identifier\n"
      + "             from location_relationship lr,\n"
      + "                  LATERAL unnest(array_append(lr.ancestry, lr.location_identifier))\n"
      + "                      WITH ORDINALITY arr(parent, position)) lr\n"
      + "                            on cast(lr.location_identifier as varchar) =\n"
      + "                               g.locationIdentifier\n"
      + "                  left join location pl on pl.identifier = lr.parent\n"
      + "     ) as p\n"
      + "         left join location_relationship pplr on p.parIdentifier = pplr.location_identifier\n"
      + "         left join location pl on pl.identifier = pplr.parent_identifier\n"
      + "WHERE pl.location_property ->> 'geographicLevel'IS NULL and p.parIdentifier IS NOT NULL\n"
      + "group by p.rdt,\n"
      + "         p.parIdentifier,\n"
      + "         p.parName,\n"
      + "         p.parGeo;",nativeQuery = true)
  List<GdrsCountsProjection> getHighestLevelPassiveCounts(UUID planIdentifier);

  @Query(value = "SELECT p.rdt,\n"
      + "       CAST(p.parIdentifier as VARCHAR) as parIdentifier,\n"
      + "       p.parName,\n"
      + "       p.parGeo,\n"
      + "       count(*)\n"
      + "FROM (\n"
      + "         SELECT g.type,\n"
      + "                g.barcode,\n"
      + "                l.location_property ->> 'geographicLevel'  as locGeo,\n"
      + "                g.rdt,\n"
      + "                pl.identifier as parIdentifier,\n"
      + "                pl.name                                    as parName,\n"
      + "                pl.location_property ->> 'geographicLevel' as parGeo\n"
      + "         FROM (\n"
      + "                  SELECT DISTINCT 'passive'                                     as type,\n"
      + "                                  CASE\n"
      + "                                      WHEN t.locIdentifier IS NULL\n"
      + "                                          THEN CAST(t.eventLocationIdentifier as varchar)\n"
      + "                                      ELSE CAST(t.locIdentifier as varchar) END as locationIdentifier,\n"
      + "                                  t.barcode,\n"
      + "                                  t.rdt,\n"
      + "                                  t.individual\n"
      + "\n"
      + "                  FROM (\n"
      + "                           SELECT l.identifier              as locIdentifier,\n"
      + "                                  arr.val ->> 'rcd_barcode' as barcode,\n"
      + "                                  arr.val ->> 'rdt'         as rdt,\n"
      + "                                  arr.val ->> 'individual'  as individual,\n"
      + "                                  e.location_identifier     as eventLocationIdentifier\n"
      + "                           from event e,\n"
      + "                                LATERAL extract_obs_fields_dynamic(\n"
      + "                                        e.additional_information,\n"
      + "                                        CAST(ARRAY ['rdt','cluster','rcd_barcode','individual'] as text[])) with ordinality arr(val, pos)\n"
      + "                                    left join location l on l.name = arr.val ->> 'cluster'\n"
      + "                           WHERE e.event_type = 'passive_case_detection'\n"
      + "                             and arr.val ->> 'rdt' is not null  and e.plan_identifier = :planIdentifier\n"
      + "                       ) as t) as g\n"
      + "                  left join location l\n"
      + "                            on cast(l.identifier as varchar) = g.locationIdentifier\n"
      + "                  left join (\n"
      + "             SELECT arr.parent, lr.location_identifier\n"
      + "             from location_relationship lr,\n"
      + "                  LATERAL unnest(array_append(lr.ancestry, lr.location_identifier))\n"
      + "                      WITH ORDINALITY arr(parent, position)) lr\n"
      + "                            on cast(lr.location_identifier as varchar) =\n"
      + "                               g.locationIdentifier\n"
      + "                  left join location pl on pl.identifier = lr.parent\n"
      + "     ) as p\n"
      + "         left join location_relationship pplr on p.parIdentifier = pplr.location_identifier\n"
      + "         left join location pl on pl.identifier = pplr.parent_identifier\n"
      + "WHERE pl.location_property ->> 'geographicLevel' = :geographicLevel and p.parIdentifier IS NOT NULL\n"
      + "group by p.rdt,\n"
      + "         p.parIdentifier,\n"
      + "         p.parName,\n"
      + "         p.parGeo;",nativeQuery = true)
  List<GdrsCountsProjection> getPassiveCounts(String geographicLevel,UUID planIdentifier);

  @Query(value = "SELECT CAST(p.parIdentifier as VARCHAR) as parIdentifier,\n"
      + "       p.parName,\n"
      + "       p.parGeo,\n"
      + "       count(*)\n"
      + "FROM (\n"
      + "         SELECT g.type,\n"
      + "                l.location_property ->> 'geographicLevel'  as locGeo,\n"
      + "                pl.identifier                              as parIdentifier,\n"
      + "                pl.name                                    as parName,\n"
      + "                pl.location_property ->> 'geographicLevel' as parGeo\n"
      + "         FROM (\n"
      + "                  SELECT DISTINCT 'index'                                                 as type,\n"
      + "                                  e.additional_information -> 'details' ->> 'location_id' as locationIdentifier,\n"
      + "\n"
      + "                                  arr.val ->> 'individual'\n"
      + "                  from event e,\n"
      + "                       LATERAL extract_obs_fields_dynamic(\n"
      + "                               e.additional_information,\n"
      + "                               CAST(ARRAY ['individual'] as text[])) with ordinality arr(val, pos)\n"
      + "\n"
      + "                  WHERE e.event_type in\n"
      + "                        ('index_case_member',\n"
      + "                         'secondary_index_case_member')  and e.plan_identifier = :planIdentifier\n"
      + "              ) as g\n"
      + "                  left join location l\n"
      + "                            on cast(l.identifier as varchar) = g.locationIdentifier\n"
      + "                  left join (\n"
      + "             SELECT arr.parent, lr.location_identifier\n"
      + "             from location_relationship lr,\n"
      + "                  LATERAL unnest(array_append(lr.ancestry, lr.location_identifier))\n"
      + "                      WITH ORDINALITY arr(parent, position)) lr\n"
      + "                            on cast(lr.location_identifier as varchar) =\n"
      + "                               g.locationIdentifier\n"
      + "                  left join location pl on pl.identifier = lr.parent\n"
      + "     ) as p\n"
      + "         left join location_relationship pplr on p.parIdentifier = pplr.location_identifier\n"
      + "         left join location pl on pl.identifier = pplr.parent_identifier\n"
      + "WHERE pl.location_property ->> 'geographicLevel' IS NULL and p.parIdentifier IS NOT NULL\n"
      + "group by p.parIdentifier,p.parName, p.parGeo;",nativeQuery = true)
  List<GdrsCountsProjection> getHighestLevelIndexCounts(UUID planIdentifier);

  @Query(value = "SELECT CAST(p.parIdentifier as VARCHAR) as parIdentifier,\n"
      + "       p.parName,\n"
      + "       p.parGeo,\n"
      + "       count(*)\n"
      + "FROM (\n"
      + "         SELECT g.type,\n"
      + "                l.location_property ->> 'geographicLevel'  as locGeo,\n"
      + "                pl.identifier                              as parIdentifier,\n"
      + "                pl.name                                    as parName,\n"
      + "                pl.location_property ->> 'geographicLevel' as parGeo\n"
      + "         FROM (\n"
      + "                  SELECT DISTINCT 'index'                                                 as type,\n"
      + "                                  e.additional_information -> 'details' ->> 'location_id' as locationIdentifier,\n"
      + "\n"
      + "                                  arr.val ->> 'individual'\n"
      + "                  from event e,\n"
      + "                       LATERAL extract_obs_fields_dynamic(\n"
      + "                               e.additional_information,\n"
      + "                               CAST(ARRAY ['individual'] as text[])) with ordinality arr(val, pos)\n"
      + "\n"
      + "                  WHERE e.event_type in\n"
      + "                        ('index_case_member',\n"
      + "                         'secondary_index_case_member')  and e.plan_identifier = :planIdentifier\n"
      + "              ) as g\n"
      + "                  left join location l\n"
      + "                            on cast(l.identifier as varchar) = g.locationIdentifier\n"
      + "                  left join (\n"
      + "             SELECT arr.parent, lr.location_identifier\n"
      + "             from location_relationship lr,\n"
      + "                  LATERAL unnest(array_append(lr.ancestry, lr.location_identifier))\n"
      + "                      WITH ORDINALITY arr(parent, position)) lr\n"
      + "                            on cast(lr.location_identifier as varchar) =\n"
      + "                               g.locationIdentifier\n"
      + "                  left join location pl on pl.identifier = lr.parent\n"
      + "     ) as p\n"
      + "         left join location_relationship pplr on p.parIdentifier = pplr.location_identifier\n"
      + "         left join location pl on pl.identifier = pplr.parent_identifier\n"
      + "WHERE pl.location_property ->> 'geographicLevel' = :geographicLevel and p.parIdentifier IS NOT NULL\n"
      + "group by p.parIdentifier,p.parName, p.parGeo;",nativeQuery = true)
  List<GdrsCountsProjection> getIndexCounts(String geographicLevel,UUID planIdentifier);



}
