package com.revealprecision.revealstreams.constants;

public interface DashboardColumns {

  //IRS
  String TOTAL_SPRAY_AREAS = "TOTAL_SPRAY_AREAS";
  String TARGET_SPRAY_AREAS = "TARGET_SPRAY_AREAS";
  String VISITED_AREAS = "VISITED_AREAS";
  String TOTAL_STRUCTURES = "TOTAL_STRUCTURES";
  String TOTAL_STRUCTURES_TARGETED = "TOTAL_STRUCTURES_TARGETED";
  String TOTAL_STRUCTURES_FOUND = "TOTAL_STRUCTURES_FOUND";
  String STRUCTURES_SPRAYED = "STRUCTURES_SPRAYED";
  String PERCENTAGE_VISITED_EFFECTIVELY = "PERCENTAGE_VISITED_EFFECTIVELY";
  String STRUCTURE_STATUS = "STRUCTURE_STATUS";
  String NO_OF_ROOMS = "NO_OF_ROOMS";
  String NO_OF_MALES = "NO_OF_MALES";
  String NO_OF_FEMALES = "NO_OF_FEMALES";
  String NO_OF_PREGNANT_WOMEN = "NO_OF_PREGNANT_WOMEN";
  String FOUND_COVERAGE = "FOUND_COVERAGE";
  String SPRAY_COVERAGE_OF_FOUND_STRUCTURES = "SPRAY_COVERAGE_OF_FOUND_STRUCTURES";
  String STRUCTURES_REMAINING_TO_SPRAY_TO_REACH_90 = "STRUCTURES_REMAINING_TO_SPRAY_TO_REACH_90";
  String REVIEWED_WITH_DECISION = "REVIEWED_WITH_DECISION";
  String MOBILIZED = "MOBILIZED";

  //Onchocerciasis
  String OFFICIAL_POP_TARGET = "OFFICIAL_POP_TARGET";
  String FIELD_VERIFIED_POP_TARGET = "FIELD_VERIFIED_POP_TARGET";
  String TOTAL_TREATED = "TOTAL_TREATED";
  String OFFICIAL_POP_TREATMENT_COVERAGE = "OFFICIAL_POP_TREATMENT_COVERAGE";
  String FIELD_VERIFIED_POP_TREATMENT_COVERAGE = "FIELD_VERIFIED_POP_TREATMENT_COVERAGE";
  String TOTAL_STRUCTURE_COUNT = "TOTAL_STRUCTURE_COUNT";
  String STRUCTURES_COMPLETE = "STRUCTURES_COMPLETE";
  String STRUCTURES_VISITED = "STRUCTURES_VISITED";
  String STRUCTURES_PARTIALLY_COMPLETE = "STRUCTURES_PARTIALLY_COMPLETE";
  String STRUCTURES_REFUSED_ABSENT = "STRUCTURES_REFUSED_ABSENT";
  String STRUCTURES_NOT_YET_VISITED = "STRUCTURES_NOT_YET_VISITED";
  String COVERAGE_OF_STRUCTURES_VISITED = "COVERAGE_OF_STRUCTURES_VISITED";
  String COVERAGE_OF_STRUCTURES_COMPLETED = "COVERAGE_OF_STRUCTURES_COMPLETED";
  String RECEIVED_BY_CDD = "RECEIVED_BY_CDD";
  String ADMINISTERED = "ADMINISTERED";
  String LOST_DAMAGED = "LOST_DAMAGED";
  String NUMBER_OF_ADVERSE_EVENTS = "NUMBER_OF_ADVERSE_EVENTS";
  String RETURNED_TO_SUPERVISOR = "RETURNED_TO_SUPERVISOR";
  String BUSINESS_STATUS = "BUSINESS_STATUS";
  String HOUSEHOLD_DISTRIBUTION = "HOUSEHOLD_DISTRIBUTION";
  String POINT_DISTRIBUTION = "POINT_DISTRIBUTION";
  String TOTAL_LIVING_ON_THE_STREET = "TOTAL_LIVING_ON_THE_STREET";
  String MALES_5_14 = "MALES_5_14";
  String MALES_15 = "MALES_15";
  String FEMALES_5_14 = "FEMALES_5_14";
  String FEMALES_15 = "FEMALES_15";
  String TOTAL_UNTREATED = "TOTAL_UNTREATED";
  String PREGNANT = "PREGNANT";
  String CHILD_UNDER_5 = "CHILD_UNDER_5";
  String SICK = "SICK";
  String ABSENT = "ABSENT";
  String REFUSAL = "REFUSAL";
  String TRAVEL = "TRAVEL";
  String PHONE_NUMBER = "PHONE_NUMBER";
  String NUMBER_OF_STRUCTURES_WITHIN_HOUSEHOLD = "NUMBER_OF_STRUCTURES_WITHIN_HOUSEHOLD";
  String HEAD_OF_HOUSE_HOLD = "HEAD_OF_HOUSE_HOLD";

}
