package com.revealprecision.revealstreams.persistence.repository.amdr;

import com.revealprecision.revealstreams.persistence.domain.amdr.AmdrData;
import com.revealprecision.revealstreams.persistence.projection.amdr.AmdrTotalsLandingPageProjection;
import com.revealprecision.revealstreams.persistence.projection.amdr.LandingPageCountsProjection;
import com.revealprecision.revealstreams.persistence.projection.amdr.LandingPageProjection;
import java.util.List;
import java.util.UUID;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.stereotype.Repository;

@Repository
public interface AmdrRepository extends JpaRepository<AmdrData, UUID> {

  List<AmdrData> findByTypeAndLocationIdIn(String type,List<UUID> locationIds);

  List<AmdrData> findByTypeAndLocationIdInAndCollectionYear(String type,List<UUID> locationIds, String collectionYear);
  List<AmdrData> findByTypeAndLocationIdInAndCollectionYearIn(String type,List<UUID> locationIds, List<String> collectionYear);

  AmdrData findByTypeAndLocationId(String type,UUID locationId);

  AmdrData findByTypeAndLocationIdAndCollectionYear(String type,UUID locationId, String collectionYear);
  List<AmdrData> findByTypeAndLocationIdAndCollectionYearIn(String type,UUID locationId, List<String> collectionYear);

  List<AmdrData> findByLocationIdInAndCollectionYear(List<UUID> locationIds, String collectionYear);
  List<AmdrData> findByLocationIdInAndCollectionYearIn(List<UUID> locationIds, List<String> collectionYear);


  List<AmdrData> findByLocationIdIn(List<UUID> locationIds);

  @Query(value = "SELECT max(ad.collection_year) from amdr.amdr_data ad", nativeQuery = true)
  long getLatestYear();


  @Query(value = "WITH monthly AS (\n"
      + "    SELECT t.year,\n"
      + "           t.month,\n"
      + "           SUM(t.case)                           AS cases,\n"
      + "           sum(t.rcd) as rcd_cases,\n"
      + "           SUM(t.passive) as passive_cases,\n"
      + "           SUM(t.has_parisitology)               AS parasitology_reports,\n"
      + "           SUM(t.has_import)                     AS imported_sequences,\n"
      + "           SUM(t.case) - SUM(t.has_parisitology) AS balance_parasitology,\n"
      + "           SUM(t.case) - SUM(t.has_import) AS balance_import\n"
      + "    FROM (\n"
      + "             SELECT t.year,\n"
      + "                   cast(t.month as int) as month,\n"
      + "                    CASE WHEN t.barcode IS NOT NULL THEN 1 ELSE 0 END                 AS case,\n"
      + "                    CASE WHEN t.type='rcd' THEN 1 ELSE 0 END as rcd,\n"
      + "                    CASE WHEN t.type='passive' THEN 1 ELSE 0 END as passive,\n"
      + "                    CASE WHEN g.parasitology_barcode IS NOT NULL THEN 1 ELSE 0 END    AS has_parisitology,\n"
      + "                    CASE WHEN import.sample_internal_id IS NOT NULL THEN 1 ELSE 0 END as has_import\n"
      + "             FROM (\n"
      + "                      SELECT DISTINCT 'rcd'                                                   AS type,\n"
      + "                                      date_part('month',\n"
      + "                                                to_date(et.operation_datetime, 'DD-MM-YYYY')) AS month,\n"
      + "                                      date_part('year',\n"
      + "                                                to_date(et.operation_datetime, 'DD-MM-YYYY')) AS year,\n"
      + "                                      et.observations -> 'rcd_barcode' ->> 0                  AS barcode\n"
      + "                      FROM event_tracker et\n"
      + "                      WHERE et.event_type = 'rcd'\n"
      + "                        AND et.observations -> 'rdt' ->> 0 = 'Positive'\n"
      + "\n"
      + "                      UNION ALL\n"
      + "\n"
      + "                      SELECT DISTINCT 'passive'                                               AS type,\n"
      + "                                      date_part('month',\n"
      + "                                                to_date(et.operation_datetime, 'DD-MM-YYYY')) AS month,\n"
      + "                                      date_part('year',\n"
      + "                                                to_date(et.operation_datetime, 'DD-MM-YYYY')) AS year,\n"
      + "                                      et.observations -> 'rcd_barcode' ->> 0                  AS barcode\n"
      + "                      FROM event_tracker et\n"
      + "                      WHERE et.event_type = 'passive_case_detection'\n"
      + "                        AND et.observations -> 'rdt' ->> 0 = 'Positive'\n"
      + "                  ) t\n"
      + "                      LEFT JOIN (\n"
      + "                 SELECT date_part('month', g.created_datetime) AS month,\n"
      + "                        date_part('year', g.created_datetime)  AS year,\n"
      + "                        g.barcode                              AS parasitology_barcode\n"
      + "                 FROM (\n"
      + "                          SELECT CAST(e.identifier AS varchar)          AS parasitology_event_identifier,\n"
      + "                                 e.created_datetime,\n"
      + "                                 CAST(e.location_identifier AS varchar) AS parasitology_location_identifier,\n"
      + "                                 e.additional_information,\n"
      + "                                 t.*\n"
      + "                          FROM event e,\n"
      + "                               LATERAL extract_obs_fields_parasitology(e.additional_information) t\n"
      + "                          WHERE e.event_type = 'parasitology'\n"
      + "                      ) g\n"
      + "             ) g ON g.parasitology_barcode = t.barcode\n"
      + "                      left join (\n"
      + "                 select ad.sample_internal_id,\n"
      + "                        date_part('month', uploaded_datetime) as month,\n"
      + "                        date_part('year', uploaded_datetime)  as year\n"
      + "                 from amdr.amdr_sample_data ad\n"
      + "                          left join amdr.amdr_import ai on ai.identifier = ad.import_id\n"
      + "                 WHERE ad.status = 'PROCESSED'\n"
      + "             ) as import on import.sample_internal_id = t.barcode\n"
      + "         ) t\n"
      + "    GROUP BY t.year, t.month\n"
      + ")\n"
      + "\n"
      + "SELECT year ,\n"
      + "       month,\n"
      + "       passive_cases as passiveCases,\n"
      + "       rcd_cases as rcdCases,\n"
      + "       cases as cases,\n"
      + "       parasitology_reports as parasitologyReports,\n"
      + "       balance_parasitology as balanceParasitology,\n"
      + "       SUM(balance_parasitology) OVER (\n"
      + "           ORDER BY year, month\n"
      + "           ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW\n"
      + "           ) AS rollingBalanceParasitology,\n"
      + "       imported_sequences as importedSequences,\n"
      + "       balance_import as balanceImport,\n"
      + "       SUM(balance_import) OVER (\n"
      + "           ORDER BY year, month\n"
      + "           ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW\n"
      + "           )  as rollingBalanceImport\n"
      + "FROM monthly\n"
      + "ORDER BY year, month;",nativeQuery = true)
  List<LandingPageProjection> getLandingPageData();


  @Query(value = "\n"
      + "    SELECT \n"
      + "           SUM(t.case)                           AS cases,\n"
      + "           sum(t.rcd) as rcdCases,\n"
      + "           SUM(t.passive) as passiveCases,\n"
      + "           SUM(t.has_parisitology)               AS parasitologyReports,\n"
      + "           SUM(t.has_import)                     AS importedSequences,\n"
      + "           SUM(t.case) - SUM(t.has_parisitology) AS balanceParasitology,\n"
      + "           SUM(t.case) - SUM(t.has_import) AS balanceImport\n"
      + "    FROM (\n"
      + "             SELECT t.year,\n"
      + "                    cast(t.month as int) as month,\n"
      + "                    CASE WHEN t.barcode IS NOT NULL THEN 1 ELSE 0 END                 AS case,\n"
      + "                    CASE WHEN t.type='rcd' THEN 1 ELSE 0 END as rcd,\n"
      + "                    CASE WHEN t.type='passive' THEN 1 ELSE 0 END as passive,\n"
      + "                    CASE WHEN g.parasitology_barcode IS NOT NULL THEN 1 ELSE 0 END    AS has_parisitology,\n"
      + "                    CASE WHEN import.sample_internal_id IS NOT NULL THEN 1 ELSE 0 END as has_import\n"
      + "             FROM (\n"
      + "                      SELECT DISTINCT 'rcd'                                                   AS type,\n"
      + "                                      date_part('month',\n"
      + "                                                to_date(et.operation_datetime, 'DD-MM-YYYY')) AS month,\n"
      + "                                      date_part('year',\n"
      + "                                                to_date(et.operation_datetime, 'DD-MM-YYYY')) AS year,\n"
      + "                                      et.observations -> 'rcd_barcode' ->> 0                  AS barcode\n"
      + "                      FROM event_tracker et\n"
      + "                      WHERE et.event_type = 'rcd'\n"
      + "                        AND et.observations -> 'rdt' ->> 0 = 'Positive'\n"
      + "\n"
      + "                      UNION ALL\n"
      + "\n"
      + "                      SELECT DISTINCT 'passive'                                               AS type,\n"
      + "                                      date_part('month',\n"
      + "                                                to_date(et.operation_datetime, 'DD-MM-YYYY')) AS month,\n"
      + "                                      date_part('year',\n"
      + "                                                to_date(et.operation_datetime, 'DD-MM-YYYY')) AS year,\n"
      + "                                      et.observations -> 'rcd_barcode' ->> 0                  AS barcode\n"
      + "                      FROM event_tracker et\n"
      + "                      WHERE et.event_type = 'passive_case_detection'\n"
      + "                        AND et.observations -> 'rdt' ->> 0 = 'Positive'\n"
      + "                  ) t\n"
      + "                      LEFT JOIN (\n"
      + "                 SELECT date_part('month', g.created_datetime) AS month,\n"
      + "                        date_part('year', g.created_datetime)  AS year,\n"
      + "                        g.barcode                              AS parasitology_barcode\n"
      + "                 FROM (\n"
      + "                          SELECT CAST(e.identifier AS varchar)          AS parasitology_event_identifier,\n"
      + "                                 e.created_datetime,\n"
      + "                                 CAST(e.location_identifier AS varchar) AS parasitology_location_identifier,\n"
      + "                                 e.additional_information,\n"
      + "                                 t.*\n"
      + "                          FROM event e,\n"
      + "                               LATERAL extract_obs_fields_parasitology(e.additional_information) t\n"
      + "                          WHERE e.event_type = 'parasitology'\n"
      + "                      ) g\n"
      + "             ) g ON g.parasitology_barcode = t.barcode\n"
      + "                      left join (\n"
      + "                 select ad.sample_internal_id,\n"
      + "                        date_part('month', uploaded_datetime) as month,\n"
      + "                        date_part('year', uploaded_datetime)  as year\n"
      + "                 from amdr.amdr_sample_data ad\n"
      + "                          left join amdr.amdr_import ai on ai.identifier = ad.import_id\n"
      + "                 WHERE ad.status = 'PROCESSED'\n"
      + "             ) as import on import.sample_internal_id = t.barcode\n"
      + "         ) t",nativeQuery = true)
  AmdrTotalsLandingPageProjection getTotalIndicators();


  @Query(value = "SELECT t.year,\n"
      + "       cast(t.month as int) as month,\n"
      + "       count(*) as cnt\n"
      + "\n"
      + "FROM (\n"
      + "         SELECT DISTINCT 'rcd'                                                   as type,\n"
      + "                         date_part('month',\n"
      + "                                   e.capture_datetime)                           AS month,\n"
      + "                         date_part('year',\n"
      + "                                   e.created_datetime)                           AS year,\n"
      + "                         e.additional_information -> 'details' ->> 'location_id' as locationIdentifier,\n"
      + "                         arr.val ->> 'rcd_barcode'                               as barcode,\n"
      + "                         arr.val ->> 'rdt'                                       as rdt,\n"
      + "                         arr.val ->> 'individual'                                as individual\n"
      + "         From event e,\n"
      + "              LATERAL extract_obs_fields_dynamic(\n"
      + "                      e.additional_information,\n"
      + "                      CAST(ARRAY ['rdt','rcd_barcode','individual'] as text[])) with ordinality arr(val, pos)\n"
      + "\n"
      + "         where e.event_type = 'rcd'\n"
      + "           and arr.val ->> 'rdt' = 'positive'\n"
      + "     ) t\n"
      + "group by t.year, t.month;",nativeQuery = true)
  List<LandingPageCountsProjection>  getRCDCountsByYearMonth();


  @Query(value = "SELECT t.year,\n"
      + "       cast(t.month as int) as month,\n"
      + "       count(*) as cnt\n"
      + "FROM (\n"
      + "         SELECT t.type,\n"
      + "                t.individual,\n"
      + "                t.locationIdentifier,\n"
      + "                t.rdt,\n"
      + "                t.barcode,\n"
      + "                date_part('month',\n"
      + "                          barcode_match.capture_datetime) AS month,\n"
      + "                date_part('year',\n"
      + "                          barcode_match.capture_datetime) AS year\n"
      + "         from (\n"
      + "                  SELECT DISTINCT 'passive'                                     as type,\n"
      + "                                  CASE\n"
      + "                                      WHEN t.locIdentifier IS NULL\n"
      + "                                          THEN CAST(t.eventLocationIdentifier as varchar)\n"
      + "                                      ELSE CAST(t.locIdentifier as varchar) END as locationIdentifier,\n"
      + "                                  t.barcode,\n"
      + "                                  t.rdt,\n"
      + "                                  t.individual\n"
      + "\n"
      + "                  FROM (\n"
      + "                           SELECT e.locIdentifier,\n"
      + "                                  e.barcode,\n"
      + "                                  e.rdt,\n"
      + "                                  e.individual,\n"
      + "                                  e.eventLocationIdentifier\n"
      + "\n"
      + "                           from amdr.passive_event e\n"
      + "                       ) as t\n"
      + "              ) as t\n"
      + "                  LEFT JOIN LATERAL (\n"
      + "             SELECT e2.capture_datetime\n"
      + "             FROM amdr.passive_event e2\n"
      + "             WHERE e2.barcode = t.barcode\n"
      + "             ORDER BY e2.capture_datetime DESC\n"
      + "             LIMIT 1\n"
      + "             ) barcode_match ON true\n"
      + "     ) t\n"
      + "group by t.year, t.month;",nativeQuery = true)
  List<LandingPageCountsProjection>  getPassiveCountsByYearMonth();

  @Query(value = "SELECT t.year,\n"
      + "       cast(t.month as int) as month,\n"
      + "       count(*) as cnt\n"
      + "FROM (\n"
      + "SELECT\n"
      + "    date_part('month',\n"
      + "              match.capture_datetime) AS month,\n"
      + "    date_part('year',\n"
      + "              match.capture_datetime) AS year,\n"
      + "       e.barcode\n"
      + " from (\n"
      + "                  SELECT DISTINCT e.barcode\n"
      + "                  FROM amdr.parasitology_event e\n"
      + "              ) as e\n"
      + "left join lateral (\n"
      + "    select e2.capture_datetime from amdr.parasitology_event e2\n"
      + "    WHERE e2.barcode = e.barcode\n"
      + "    order by e2.capture_datetime desc\n"
      + "    limit 1\n"
      + "    ) match on true\n"
      + "     ) t\n"
      + "group by t.year, t.month;",nativeQuery = true)
  List<LandingPageCountsProjection>  getParasitologyCountsByYearMonth();

  @Query(value = "SELECT t.year,\n"
      + "       cast(t.month as int) as month,\n"
      + "       count(*) as cnt\n"
      + "FROM (\n"
      + "select ad.sample_internal_id,\n"
      + "       date_part('month', uploaded_datetime) as month,\n"
      + "       date_part('year', uploaded_datetime)  as year\n"
      + "from amdr.amdr_sample_data ad\n"
      + "         left join amdr.amdr_import ai on ai.identifier = ad.import_id\n"
      + "WHERE ad.status = 'PROCESSED'\n"
      + "     ) t\n"
      + "group by t.year, t.month;",nativeQuery = true)
  List<LandingPageCountsProjection> getImportCountsByYearMonth();
}
