package com.revealprecision.revealstreams.persistence.repository.amdr;

import com.revealprecision.revealstreams.persistence.domain.amdr.AmdrDataCalMat;
import com.revealprecision.revealstreams.persistence.projection.amdr.AmdrDataCalcMatProjection;
import java.util.List;
import java.util.UUID;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.stereotype.Repository;

@Repository
public interface AmdrDataCalMatRepository extends JpaRepository<AmdrDataCalMat, Integer> {


  @Query(value = "SELECT "
      + "     cast(jsonb_build_object(\n"
      + "\n"
      + "    'kelch13',jsonb_build_object(\n"
      + "        'kelch_13', jsonb_build_object(\n"
      + "                'wild', sum(adcm.kelch_13wild),\n"
      + "                'mono', sum(adcm.kelch_13mono),\n"
      + "                'mixed', sum(adcm.kelch_13mixed),\n"
      + "                'totalRecs', sum(adcm.kelch_13totalrecs)\n"
      + "            ),\n"
      + "        'total',jsonb_build_object(\n"
      + "                'wild', sum(adcm.kelchwild),\n"
      + "                'mono', sum(adcm.kelchMono),\n"
      + "                'mixed', sum(adcm.kelchMixed),\n"
      + "                'totalRecs', sum(adcm.kelchTotalrecs)\n"
      + "            )),\n"
      + "    'pfcrt',jsonb_build_object(\n"
      + "        'pfcrt_72', jsonb_build_object(\n"
      + "                'wild', sum(adcm.pfcrt_72wild),\n"
      + "                'mono', sum(adcm.pfcrt_72mono),\n"
      + "                'mixed', sum(adcm.pfcrt_72mixed),\n"
      + "                'totalRecs', sum(adcm.pfcrt_72totalrecs)\n"
      + "            ),\n"
      + "\n"
      + "        'pfcrt_74', jsonb_build_object(\n"
      + "                'wild', sum(adcm.pfcrt_74wild),\n"
      + "                'mono', sum(adcm.pfcrt_74mono),\n"
      + "                'mixed', sum(adcm.pfcrt_74mixed),\n"
      + "                'totalRecs', sum(adcm.pfcrt_74totalrecs)\n"
      + "            ),\n"
      + "\n"
      + "        'pfcrt_75', jsonb_build_object(\n"
      + "                'wild', sum(adcm.pfcrt_75wild),\n"
      + "                'mono', sum(adcm.pfcrt_75mono),\n"
      + "                'mixed', sum(adcm.pfcrt_75mixed),\n"
      + "                'totalRecs', sum(adcm.pfcrt_75totalrecs)\n"
      + "            ),\n"
      + "\n"
      + "        'pfcrt_76', jsonb_build_object(\n"
      + "                'wild', sum(adcm.pfcrt_76wild),\n"
      + "                'mono', sum(adcm.pfcrt_76mono),\n"
      + "                'mixed', sum(adcm.pfcrt_76mixed),\n"
      + "                'totalRecs', sum(adcm.pfcrt_76totalrecs)\n"
      + "            ),\n"
      + "        'total',jsonb_build_object(\n"
      + "                'wild', sum(adcm.pfcrtwild),\n"
      + "                'mono', sum(adcm.pfcrtmono),\n"
      + "                'mixed', sum(adcm.pfcrtmixed),\n"
      + "                'totalRecs', sum(adcm.pfcrttotalrecs)\n"
      + "            )),\n"
      + "   'pfdhfr', jsonb_build_object(\n"
      + "        'pfdhfr_51', jsonb_build_object(\n"
      + "                'wild', sum(adcm.pfdhfr_51wild),\n"
      + "                'mono', sum(adcm.pfdhfr_51mono),\n"
      + "                'mixed', sum(adcm.pfdhfr_51mixed),\n"
      + "                'totalRecs', sum(adcm.pfdhfr_51totalrecs)\n"
      + "            ),\n"
      + "\n"
      + "        'pfdhfr_59', jsonb_build_object(\n"
      + "                'wild', sum(adcm.pfdhfr_59wild),\n"
      + "                'mono', sum(adcm.pfdhfr_59mono),\n"
      + "                'mixed', sum(adcm.pfdhfr_59mixed),\n"
      + "                'totalRecs', sum(adcm.pfdhfr_59totalrecs)\n"
      + "            ),\n"
      + "\n"
      + "        'pfdhfr_108', jsonb_build_object(\n"
      + "                'wild', sum(adcm.pfdhfr_108wild),\n"
      + "                'mono', sum(adcm.pfdhfr_108mono),\n"
      + "                'mixed', sum(adcm.pfdhfr_108mixed),\n"
      + "                'totalRecs', sum(adcm.pfdhfr_108totalrecs)\n"
      + "            ),\n"
      + "\n"
      + "        'pfdhfr_164', jsonb_build_object(\n"
      + "                'wild', sum(adcm.pfdhfr_164wild),\n"
      + "                'mono', sum(adcm.pfdhfr_164mono),\n"
      + "                'mixed', sum(adcm.pfdhfr_164mixed),\n"
      + "                'totalRecs', sum(adcm.pfdhfr_164totalrecs)\n"
      + "            ),\n"
      + "        'total',jsonb_build_object(\n"
      + "                'wild', sum(adcm.pfdhfrWild),\n"
      + "                'mono', sum(adcm.pfdhfrMono),\n"
      + "                'mixed', sum(adcm.pfdhfrMixed),\n"
      + "                'totalRecs', sum(adcm.pfdhfrTotalrecs)\n"
      + "            )),\n"
      + "    'pfdhps',jsonb_build_object(\n"
      + "        'pfdhps_436', jsonb_build_object(\n"
      + "                'wild', sum(adcm.pfdhps_436wild),\n"
      + "                'mono', sum(adcm.pfdhps_436mono),\n"
      + "                'mixed', sum(adcm.pfdhps_436mixed),\n"
      + "                'totalRecs', sum(adcm.pfdhps_436totalrecs)\n"
      + "            ),\n"
      + "\n"
      + "        'pfdhps_437', jsonb_build_object(\n"
      + "                'wild', sum(adcm.pfdhps_437wild),\n"
      + "                'mono', sum(adcm.pfdhps_437mono),\n"
      + "                'mixed', sum(adcm.pfdhps_437mixed),\n"
      + "                'totalRecs', sum(adcm.pfdhps_437totalrecs)\n"
      + "            ),\n"
      + "\n"
      + "        'pfdhps_540', jsonb_build_object(\n"
      + "                'wild', sum(adcm.pfdhps_540wild),\n"
      + "                'mono', sum(adcm.pfdhps_540mono),\n"
      + "                'mixed', sum(adcm.pfdhps_540mixed),\n"
      + "                'totalRecs', sum(adcm.pfdhps_540totalrecs)\n"
      + "            ),\n"
      + "\n"
      + "        'pfdhps_581', jsonb_build_object(\n"
      + "                'wild', sum(adcm.pfdhps_581wild),\n"
      + "                'mono', sum(adcm.pfdhps_581mono),\n"
      + "                'mixed', sum(adcm.pfdhps_581mixed),\n"
      + "                'totalRecs', sum(adcm.pfdhps_581totalrecs)\n"
      + "            ),\n"
      + "\n"
      + "        'pfdhps_613', jsonb_build_object(\n"
      + "                'wild', sum(adcm.pfdhps_613wild),\n"
      + "                'mono', sum(adcm.pfdhps_613mono),\n"
      + "                'mixed', sum(adcm.pfdhps_613mixed),\n"
      + "                'totalRecs', sum(adcm.pfdhps_613totalrecs)\n"
      + "            ),\n"
      + "        'total',jsonb_build_object(\n"
      + "                'wild', sum(adcm.pfdhpsWild),\n"
      + "                'mono', sum(adcm.pfdhpsMono),\n"
      + "                'mixed', sum(adcm.pfdhpsMixed),\n"
      + "                'totalRecs', sum(adcm.pfdhpsTotalrecs)\n"
      + "            )),\n"
      + "    'pfmdr1',jsonb_build_object(\n"
      + "        'pfmdr1_86', jsonb_build_object(\n"
      + "                'wild', sum(adcm.pfmdr1_86wild),\n"
      + "                'mono', sum(adcm.pfmdr1_86mono),\n"
      + "                'mixed', sum(adcm.pfmdr1_86mixed),\n"
      + "                'totalRecs', sum(adcm.pfmdr1_86totalrecs)\n"
      + "            ),\n"
      + "\n"
      + "        'pfmdr1_184', jsonb_build_object(\n"
      + "                'wild', sum(adcm.pfmdr1_184wild),\n"
      + "                'mono', sum(adcm.pfmdr1_184mono),\n"
      + "                'mixed', sum(adcm.pfmdr1_184mixed),\n"
      + "                'totalRecs', sum(adcm.pfmdr1_184totalrecs)\n"
      + "            ),\n"
      + "\n"
      + "        'pfmdr1_1246', jsonb_build_object(\n"
      + "                'wild', sum(adcm.pfmdr1_1246wild),\n"
      + "                'mono', sum(adcm.pfmdr1_1246mono),\n"
      + "                'mixed', sum(adcm.pfmdr1_1246mixed),\n"
      + "                'totalRecs', sum(adcm.pfmdr1_1246totalrecs)\n"
      + "            ),\n"
      + "        'total',jsonb_build_object(\n"
      + "                'wild', sum(adcm.pfmdr1Wild),\n"
      + "                'mono', sum(adcm.pfmdr1Mono),\n"
      + "                'mixed', sum(adcm.pfmdr1Mixed),\n"
      + "                'totalRecs', sum(adcm.pfmdr1Totalrecs)\n"
      + "            ))\n"
      + "\n"
      + "    )as varchar)  AS markers\n"
      + "\n"
      + "from amdr.amdr_data_calc_mat adcm"
      + " WHERE adcm.ancestor in :ancestor and adcm.collection_year in :collectionYear\n"
      + "",nativeQuery = true)
  AmdrDataCalcMatProjection getAmdrDataCalcMatIdsBy(List<UUID> ancestor, List<Double> collectionYear);

}
